# Generated by Django 3.1.3 on 2022-03-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20220323_0708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='chocies',
            new_name='choices',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_selected',
            field=models.IntegerField(default=0),
        ),
    ]
